[package]
name = "geompix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

gtk4 = "0.4.6"
gdk4 = "0.4.6"
piet = "0.5.0"
piet-cairo = "0.5.0"
kurbo = "^0.8.2"
graphene-rs = "^0.15.1"
